name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    container: espressif/idf:v5.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: apt-get update && apt-get install autoconf libtool pkg-config protobuf-compiler libprotoc-dev -y

      - name: Install protobuf-c
        run: |
          git clone https://github.com/protobuf-c/protobuf-c /libs/protobuf-c
          cd /libs/protobuf-c
          ./autogen.sh
          ./configure --prefix=/usr
          make
          make install

      - name: Prepare workspace
        run: |
          mkdir _build
          cp sdkconfig.defaults sdkconfig

      - name: Prepare environment
        run: |
          echo /opt/esp/tools/cmake/3.24.0/bin >> $GITHUB_PATH
          echo /opt/esp/tools/xtensa-esp-elf/esp-13.2.0_20240530/xtensa-esp-elf/bin >> $GITHUB_PATH

      - name: Configure
        working-directory: _build
        run: cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=/opt/esp/idf/tools/cmake/toolchain-esp32s2.cmake -DTARGET=esp32s2 -DPYTHON=/opt/esp/python_env/idf5.3_py3.10_env/bin/python

      - name: Build
        working-directory: _build
        run: ninja
