name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: espressif/idf:v5.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install clang-format -y

      - name: Lint
        run: find src/ -name "*.h" -o -name "*.c" | xargs clang-format --dry-run -Werror
